Create Template button redirects to create template page
Likhovodov/Simulated-Conversations pull request #30
Opened 2021-02-01 05:29 UTC by kaigoos

"Create template" button redirects to create new conversation template page created by David.

Table for templates and folders now have pagination. Pagination is set at 5 for now but can be changed later once css is added to the page.

Search bar also added for template and folders.Searching for a folder while viewing the contents of a specific folder should keep you inside of that folder. Searching for a template while inside a folder should only show templates that are in that folder. 

Searching for a template will query both the name and description for the value. This can be changed if someone thinks a toggle option between the two fields is better. Also if anybody thinks filtering by creation date is also necessary I can look into doing that too.

2021-02-02 22:48 UTC, BroughtMyPopcorn requested changes
Everything works well, no real critiques. I like that the template search includes both the name and description. I think filtering by creation date would be nice but doesn't need to happen on this ticket. Only requesting changes for the missing slashes because we just fixed up all of the url's.

2021-02-02 22:48 UTC, BroughtMyPopcorn commented on simcon_project/conversation_templates/urls/templates_urls.py
> +    path('redirect/template', RedirectToTemplateCreation.as_view(), name="redirect-to-template-creation"),
the url's on 13 and 14 should have slashes at the end

2021-02-02 22:53 UTC, BroughtMyPopcorn commented on simcon_project/templates/template_management/main_view.html
> +            <form action="{% url "management:main"%}" method="get">
PyCharm is upset with the use of the double-quotes around the url shortcut. single-quotes make it happy.

2021-02-03 05:50 UTC, BroughtMyPopcorn approved these changes

2021-02-04 23:39 UTC, Likhovodov approved these changes
Looks good

2021-02-05 00:18 UTC, merged