Michael/symco12/Password Reset
Likhovodov/Simulated-Conversations pull request #34
Opened 2021-02-05 02:33 UTC by Mkay971

This is for the password reset form through email from the login page. simply enter in a student or researchers email and they will be sent a link to reset their password, and then directed to login.

2021-02-05 06:35 UTC, ericharper1 commented on simcon_project/simcon_project/urls.py
> +    path('password-reset-complete/', views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name="password_reset_confirm"),
I'm gonna be a jerk here but for the url name, it should be hyphen-case instead of snake_case :)

2021-02-05 06:35 UTC, ericharper1 commented on simcon_project/templates/registration/login.html
> +    <a href="/password-reset/">Forgot Password?</a>
use the url template tag and the url name here instead of hard-coded url

2021-02-05 06:36 UTC, ericharper1 commented on simcon_project/templates/registration/password_reset_complete.html
> +    <a href="/">Sing In Here</a>
Typo on line 5

2021-02-05 06:37 UTC, ericharper1 commented on simcon_project/users/views/password_reset.py
> +                          + uid + '/' + token +'/' '\n'
Header and message should be more tailored for password reset

2021-02-05 06:40 UTC, ericharper1 requested changes
Works well and guards against invalid input. Just made some stylistic comments

2021-02-05 21:04 UTC, ericharper1 commented on simcon_project/templates/registration/password_reset_complete.html
> +    <a href="{% url 'login' %}">Sing In Here</a>
Typo in <a> tag

2021-02-05 21:06 UTC, ericharper1 approved these changes, later dismissed
Awesome!

2021-02-06 00:07 UTC, BroughtMyPopcorn commented on simcon_project/users/views/password_reset.py
> +    return render(request, 'registration/password_reset.html', {"form": PassReset()})
newline

2021-02-06 00:07 UTC, BroughtMyPopcorn commented on simcon_project/users/views/password_reset.py
> +                    subject = 'Reset Your Simulated conversations account password'
C on conversations. nit picky, I know

2021-02-06 00:08 UTC, BroughtMyPopcorn commented on simcon_project/users/views/student_management.py
> +                    subject = 'Activate Your Simulated conversations account'
C on conversations

2021-02-06 00:11 UTC, BroughtMyPopcorn submitted a review, later dismissed
Works great. Suggested small changes. Approving anyway, none of my changes should stop this from getting merged. We can fix later.

2021-02-06 01:34 UTC, rosasck approved these changes, later dismissed

2021-02-06 01:35 UTC, rosasck reviewed
but fix devins changes plzz

2021-02-08 22:35 UTC, BroughtMyPopcorn approved these changes

2021-02-08 23:02 UTC, JerCarnahan approved these changes

2021-02-08 23:35 UTC, merged