tables good, empty tables gooood
Likhovodov/Simulated-Conversations pull request #92
Opened 2021-03-07 03:28 UTC by rosasck

2021-03-08 18:15 UTC, BroughtMyPopcorn commented
Could be wrong, but I think we wanted to have the table headers shown even if there wasn't anything to display, now there's just nothing showing on these pages.

2021-03-11 08:35 UTC, ericharper1 requested changes
This occurred when I tried to delete a student response from my researcher table. :(

![image](https://user-images.githubusercontent.com/47010730/110758706-aa611780-8201-11eb-9c34-36941d6c5c6d.png)

2021-03-18 03:19 UTC, Likhovodov approved these changes
Looks good. If we could get a row indicating that the table is empty somehow, it would be great though it's far from a necessity.

2021-03-18 03:19 UTC, Likhovodov commented on simcon_project/simcon_project/settings.py
> +EMAIL_HOST_PASSWORD = 'FAKEPASSWORD1102302032198'
Undo

2021-03-18 20:45 UTC, JerCarnahan approved these changes

2021-04-12 04:54 UTC, merged